name: Deploy to HuggingFace
on: 
  push:
    branches:
      - main

jobs:

  deploy:
    runs-on: windows-latest
    steps:
    
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
            
    - name: Install dependencies
      run: |
        pip install pytesseract
        pip install opencv-python
    
    - name: Run image to text
      run: |
        python main.py
        
    - name: Deploy to HuggingFace 
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}  
      run: |
       pip install huggingface_hub
       huggingface-cli login --token %HF_TOKEN%  
       huggingface-cli repo push -space myusername
